### ISSUE TITLE
Images not working on demo site

### ISSUE THREAD

**Issue by nutritioneve** [lukaskoeller/gridsome-starter-strapi#2]
Just so you know, the demo site's images are not loading as they try to load from `localhost:1337.....`

**Comment by lukaskoeller** [comment]
Thanks @nutritioneve for letting me know. I am aware of it and will fix it asap.

**Comment by lukaskoeller** [comment]
**gridsome.server.js**

```javascript
api.onCreateNode(options => {
    const filePath = `./src/assets/images/${options.image.hash + options.image.ext}`;

    http.get(`http://localhost:1337${options.image.url}`, (response) => {
      options.image.url = path.resolve(__dirname, filePath);

      const file = fs.createWriteStream(filePath);
      response.pipe(file);
    })
  })
```
Remote images are now downloaded and saved locally. Thus, the website's images are saved in `/static` in the `/dist` folder.
