### ISSUE TITLE
Q: Save new images to Gridsome when server is running

### ISSUE THREAD

**Issue by kwiat1990** [lukaskoeller/gridsome-starter-strapi#7]
Hi,

I have implemented your function to move all medias from Strapi into Gridsome's asset directory, so that all feature of the `g-image` can be used. And that works very well. I have encountered one problem though. If my server is running and I upload a new image in Strapi, then there is no chance that this image will be moved to assets directory. The server must be restarted.

Is there any way to do that while the server is running? I'm looking for some solution, which would work on production as well. Right know it seems that to make it working, the whole `g-image` functionality needs to be implemented in some custom component, which would then use responsive image variants that Strapi creates for every image.

**Comment by lukaskoeller** [comment]
> Is there any way to do that while the server is running?
Hi @kwiat1990! I will soon work on this repo anyway, and will have a look into this then as well.

If you want to update your Gridsome page in production when you make changes in Strapi, then this should probably happen through a **Webhook** that you configure within the hosting platform (e.g. Netflify). You can read more under [Strapi Webhooks](https://strapi.io/blog/webhooks) or take inspiration of the [tutorial for Gatsby](https://strapi.io/blog/building-a-static-website-using-gatsby-and-strapi#12webhookswithgatsbystrapi) and then apply the approach for gridsome.

As soon as I will have time to work on this repo, I will also try to provide documentation on how to deploy the site properly

**Comment by kwiat1990** [comment]
@lukaskoeller I misunderstood the JAM concept at the beginning. It's all clear to me now.

I wonder if you have encountered some problems if connecting to Strapi over https? As soon as I moved from local development to production build the function for fetching images directly from Strapi doesn't work anymore, even though I use `https` module instead `http`. I can see that I still connect to Strapi but the downloaded images are somehow corrupted and the `url` of images doesn't get replaced with Gridsome's image object but are `null`.

**Comment by lukaskoeller** [comment]
I only can say that the [Starter hosted on Netlify](https://gridsome-starter-strapi.netlify.app) is not connected to strapi in any way (no webhook or similar). After the build, all links are relative, included locally (since they were downloaded) and thus do not refer to an external resource (thus no cors or other problems). I simply uploaded the build version of the starter to Netlify.

**Comment by kwiat1990** [comment]
Yeah it is not connected to Strapis right after you download all the images. It was a restriction on my server, which blocks hotlinking for every image ressource unless it is on the white list. Then it works like earlier 🙂
