### ISSUE TITLE
Converting rich text to html

### ISSUE THREAD

**Issue by liamb13** [lukaskoeller/gridsome-starter-strapi#9]
Could the rich text section be converted to HTML instead of with white-space: pre-line to allow for more customisation around paragraphs?

**Comment by lukaskoeller** [comment]
Hi @liamb13. Sorry for being so so late...
I finally made a minor update to the repository, added *rich text* via Strapi on the `About` page and edited the `README` accordingly. I will close this issue on this behalf

See demo page: https://gridsome-starter-strapi.netlify.app/about/
